const express    = require('express');
const router     = express.Router();
const admin      = require('../controllers/admin.controller');
const payment    = require('../controllers/payment.controller');
const company    = require('../controllers/company.controller');
const { protect, adminOnly, superAdminOnly, hasPermission } = require('../middleware/auth.middleware');

router.get('/settings/bank/public', admin.getBankDetails);
router.use(protect);
router.use(adminOnly);
router.get('/dashboard',                   admin.getDashboard);
router.get('/users',                       admin.getUsers);
router.get('/users/:id',                   admin.getUserById);
router.patch('/users/:id/status',          admin.updateUserStatus);
router.delete('/users/:id',                admin.deleteUser);
router.get('/user-packages',               admin.getUserPackages);
router.get('/jobs',                        admin.getAllJobs);
router.get('/companies',                   company.getAllCompaniesAdmin);
router.patch('/companies/:id/verify',      company.verifyCompany);
router.get('/reports',                     admin.getReports);
router.patch('/reports/:id',               admin.resolveReport);
router.get('/activity-logs',               admin.getActivityLogs);
router.get('/invoices',                    admin.getInvoices);
router.get('/bank-transfers',              admin.getPendingBankTransfers);
router.patch('/bank-transfers/:invoiceId/approve', payment.approveBankTransfer);
router.patch('/bank-transfers/:invoiceId/status',  payment.updateBankTransferStatus);
router.get('/settings/bank',               admin.getBankDetails);
router.get('/refunds',         protect, adminOnly, hasPermission('refunds'),   admin.getRefundRequests);
router.patch('/refunds/:invoiceId', protect, adminOnly, hasPermission('refunds'), admin.processRefund);
router.post('/broadcast',      protect, adminOnly, hasPermission('broadcast'), admin.sendBroadcast);
router.post('/categories',     protect, adminOnly, hasPermission('categories'), admin.createCategory);
router.patch('/categories/:id',protect, adminOnly, hasPermission('categories'), admin.updateCategory);
router.delete('/categories/:id',protect,adminOnly, hasPermission('categories'), admin.deleteCategory);
router.get('/packages-list',   protect, adminOnly, hasPermission('packages'), admin.getPackagesList);
router.get('/revenue',    protect, adminOnly, hasPermission('revenue'),    admin.getRevenueReport);
router.get('/analytics',  protect, adminOnly, hasPermission('analytics'),  admin.getPlatformAnalytics);

router.use(superAdminOnly);
router.get('/admins',                      admin.getAdmins);
router.post('/admins',                     admin.createAdmin);
router.patch('/admins/:id/status',         admin.updateAdminStatus);
router.delete('/admins/:id',               admin.deleteAdmin);
router.get('/system-errors',               admin.getSystemErrors);
router.get('/system-errors/all',           admin.getAllSystemErrors);
router.get('/settings',                    admin.getSettings);
router.patch('/settings',                  admin.updateSettings);
router.patch('/settings/bank',             admin.updateBankDetails);
router.post('/packages',                   admin.createPackage);
router.patch('/packages/:id',              admin.updatePackage);
router.delete('/packages/:id',             admin.deletePackage);
router.post('/assign-package',             admin.assignPackage);
router.post('/cache/clear',                admin.clearCache);
router.get('/admins/:id/permissions',    admin.getAdminPermissions);
router.patch('/admins/:id/permissions',  admin.updateAdminPermissions);

module.exports = router;